### ISSUE TITLE
Rewrite easymock response path

### ISSUE THREAD

**Issue by ValeryIvanov** [CyberAgent/node-easymock#59]
I want to use variable in config.json to rewrite calls.

Lets say I have some `id = 1234`

Then if I access `localhost:3000/mock_data/someRequest.do`, easymock would look for response in 1234 folder like `mock_data/1234/someRequest.do_get.json` instead.

This is how I thought this should work but it does not

    {
      "variables": {
        "id": "1234"
      },
      "proxy": {
        "server": "http://localhost:3000/mock_data",
        "default": true,
        "calls": {
          "mock_data/#{id}": true
        }
      }
    }

What exactly does default property and calls boolean value true in that example do?

**Comment by pboos** [comment]
You should be able to use regex inside the calls. #{id} won't work.

This feature is not documented but was added here: https://github.com/CyberAgent/node-easymock/commit/791410fd93ac75f6ae82b3fc27ab2c43609fd700

Will probably have to document this at some point.

As well to your information, proxy is only needed if you actually want to forward it to somewhere else. I think using localhost:3000 there shows you might be doing something wrong (but maybe there is a good reason for it, that would be interesting to hear).

Best is probably to turn off the proxy config default: false and no calls. And setup the routes of the mock server like this:

```
    {
      .....,
      "routes": [
        "/mock_data/:id/someRequest.do"
      ]
    }
```

I hope this solves your problem. If not, please reopen the issue.

**Comment by ValeryIvanov** [comment]
For some reason this configuration you described does not work, it responses with the same path file.

**Comment by pboos** [comment]
Reading through your post again I am not 100% sure what you are trying to do.

```GET localhost:3000/mock_data/doRequest.do``` should return the file ```mock_data/1234/doRequest.do_get.json``` ?

Why does the 1234 have to be added in there?

Wouldn't it be good enough if ```GET localhost:3000/mock_data/1234/doRequest.do``` would return ```/mock_data/id/doRequest.do_get.json```?

Normally what one wants is to have routes like /user/{id} that the always return the same file so you do not have to create 1000 files.

Or maybe I am totally misunderstanding you.

**Comment by ValeryIvanov** [comment]
This is my full setup

C:\project\config.json

    {
      "variables": {
        "id": "1234"
      },
      "routes": [
        "/mock_data/:id/someRequest.do"
      ]
    }

C:\project\mock_data\1234\someRequest.do_get.json

    ["haha"]


Running easymock in `C:\project`


1) Opening url in browser `http://localhost:3000/mock_data/someRequest.do`

LOGS

    Request: GET /mock_data/someRequest.do
    ==> C:\project//mock_data/someRequest.do_get.json



2) Opening url in browser `http://localhost:3000/mock_data/1234/someRequest.do`

LOGS

    Request: GET /mock_data/1234/someRequest.do
    ==> C:\project//mock_data/id/someRequest.do_get.json


3) Opening url in browser `http://localhost:3000/someRequest.do`

LOGS

    Request: GET /someRequest.do
    ==> C:\project//someRequest.do_get.json

**Comment by ValeryIvanov** [comment]
I on the other hand have to create 1000 files :D 

For every user id I want to return totally different configuration.

This user id is in my application set via some request as session and this mock server should somehow remember it. I was thinking like creating custom responses for certain users to test different scenarios. So for every user there is a folder with id as folder name with all request responses. Now to test this user I just change variable id in config.json and get responses for that user.

**Comment by pboos** [comment]
> 2) Opening url in browser http://localhost:3000/mock_data/1234/someRequest.do
> 
> LOGS
> 
> Request: GET /mock_data/1234/someRequest.do
> ==> C:\project//mock_data/id/someRequest.do_get.json

This shows the normal use case. Int his case the file would be as mentioned in the logs: ```C:\project//mock_data/id/someRequest.do_get.json```. And no matter if 1234 or anything else, it will always be that file.

----
But if you want different responses for every id, then you really do have to create each file. Then you can remove the route and create the files with the id in the path like ```C:\project//mock_data/1234/someRequest.do_get.json```.

**Comment by ValeryIvanov** [comment]
Yes I created file C:\project//mock_data/1234/someRequest.do_get.json but how can I get it with call localhost:3000/mock_data/someReqest.do

**Comment by pboos** [comment]
The question is, why do you even need to be able to get it through that call? One easy way though would be by creating that file and redirecting the call like this:

C:\project//mock_data/someRequest.do_get.json
```
< @status 302
< @header Location: http://localhost:3000/mock_data/1234/someRequest.do
```

**Comment by ValeryIvanov** [comment]
Yeah that is exactly what I need. This solution actually solves two needs

1) gives me ability to configure responses for different users
2) gives me ability to configure responses independent of user

Thanks!
