### ISSUE TITLE
Support node 10 and sqlite3 ^4.0.1

### ISSUE THREAD

**Issue by sbley** [CyberAgent/node-easymock#71]
Current easymock 0.2.28 cannot be run on node 10 because it depends on sqlite3 version 3.1.10. This version is not compatible with node 10. Only sqlite3 version ^4.0.1 is supported on node 10.

Could you please provide an update of easymock compatible with node 10?

**Comment by pboos** [comment]
Sorry for the LONG delay. Now working on node 10 as of easymock v0.2.29
